# Generated by Django 4.2.5 on 2024-03-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_1', '0005_remove_registar_create_at_registar_create_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registar',
            new_name='Registar1',
        ),
    ]
