# Generated by Django 4.2.5 on 2024-03-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_1', '0006_rename_registar_registar1'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
