# Generated by Django 4.2.5 on 2024-03-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_1', '0008_registar1_class_user_registar1_gender_registar1_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=80)),
                ('student_name', models.CharField(max_length=80)),
                ('year_of_report', models.CharField(max_length=12)),
                ('city_driving', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0000000', max_length=3)),
                ('suburbs_driving', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0000000', max_length=3)),
                ('vehicle_parking', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0000000', max_length=3)),
                ('driving_behavior', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0000000', max_length=3)),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
    ]
